
- name: install package java-common
  package:
    name: java-common
    update_cache: true

- name: check the java is installed or not
  stat:
    path: /usr/lib/jvm/java-11-amazon-corretto/bin/java
  register: stat_java

- name: "including installation task for {{ ansible_os_family }}"
  include_tasks: "install_binary_{{ ansible_os_family }}.yml"
  when: not stat_java.stat.exists

- name: check the binary file already downloaded or not
  stat: 
    path: "/opt//kafka_2.13-{{ kafka_version }}"
  register: kafka_stat

- block:
    - name: download the binary file of the kafka
      get_url:
        url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz"
        dest: "/tmp/kafka_2.13-{{ kafka_version }}.tgz"

    - name: make the kafka directory
      file:
        path: "/kafka_2.13-{{ kafka_version }}"
        state: directory

    - name: unarchive the kafka binary
      unarchive:
        src: "/tmp/kafka_2.13-{{ kafka_version }}.tgz"
        dest: "/opt/"
  when: not kafka_stat.stat.exists

- name: remove the tempfile
  file: 
    path: "/tmp/kafka_2.13-{{ kafka_version }}"
    state: absent

- name: set the enviroment variable of the kafka binary
  lineinfile:
    path: ~/.bashrc
    line: "PATH=\"$PATH:/opt/kafka_2.13-{{ kafka_version }}/bin\""

- name: source the ~/.bashrc file
  shell: source ~/.bashrc
  args:
    executable: /bin/bash
