
- name: install package java-common
  apt:
    name: java-common
    update_cache: true

- name: check the java is installed or not
  stat:
    path: /usr/lib/jvm/java-11-amazon-corretto/bin/java
  register: stat_java

- name: install java using the link
  apt:
    deb: https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.deb
    state: present
  when: not stat_java.stat.exists

- name: check the binary file already downloaded or not
  stat: 
    path: "{{ default_kafka_directory }}/kafka_2.13-{{ kafka_version }}"
  register: kafka_stat

- block:
    - name: download the binary file of the kafka
      get_url:
        url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz"
        dest: "/tmp/kafka_2.13-{{ kafka_version }}.tgz"

    - name: make the kafka directory
      file:
        path: "/kafka_2.13-{{ kafka_version }}"
        state: directory

    - name: unarchive the kafka binary
      unarchive:
        src: "/tmp/kafka_2.13-{{ kafka_version }}.tgz"
        dest: "{{ default_kafka_directory }}"
  when: not kafka_stat.stat.exists

- name: remove the tempfile
  file: 
    path: "/tmp/kafka_2.13-{{ kafka_version }}"
    state: absent



# For RPM Packages
#https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.rpm

















