
- name: install package java-common
  apt:
    name: java-common
    update_cache: true

- name: install java using the link
  apt:
    deb: https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.deb
    state: present

- name: download the binary file of the kafka
  get_url:
    url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz"
    dest: "/tmp/kafka_2.13-{{ kafka_version }}.tgz"

- name: make the kafka directory
  file:
    path: "/kafka_2.13-{{ kafka_version }}"
    state: directory

- name: unarchive the kafka binary
  unarchive:
    src: "/tmp/kafka_2.13-{{ kafka_version }}.tgz"
    dest: /

- name: remove the tempfile
  file: 
    path: "~/kafka_2.13-{{ kafka_version }}"
    state: absent



# For RPM Packages
#https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.rpm

















